baseURL = 'https://vanilla.sh/'
languageCode = 'en-GB'
title = 'Vanilla.sh'
theme = 'vanillash'

disableKinds = ["taxonomy", "term"]
summaryLength = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
